export const FETCHING_MESSANGERS = "FETCHING_MESSANGERS";
export const FETCH_MESSANGERS_SUCCESS = "FETCH_MESSANGERS_SUCCESS";
export const UPDATING_MESSANGER = "UPDATING_MESSANGER";
export const UPDATE_MESSANGER_SUCCESS = "UPDATE_MESSANGER_SUCCESS";
export const MESSANGERS_ERROR = "MESSANGERS_ERROR";
