export const FETCHING_CALENDARS = "FETCHING_CALENDARS";
export const FETCH_CALENDARS_SUCCESS = "FETCH_CALENDARS_SUCCESS";
export const ADDING_CALENDAR = "ADDING_CALENDAR";
export const ADD_CALENDAR_SUCCESS = "ADD_CALENDAR_SUCCESS";
export const UPDATING_CALENDAR = "UPDATING_CALENDAR";
export const UPDATE_CALENDAR_SUCCESS = "UPDATE_CALENDAR_SUCCESS";
export const CALENDARS_ERROR = "CALENDARS_ERROR";
