export const FETCHING_FILTERS = "FETCHING_FILTERS";
export const FETCH_FILTERS_SUCCESS = "FETCH_FILTERS_SUCCESS";
export const UPDATING_FILTER = "UPDATING_FILTER";
export const UPDATE_FILTER_SUCCESS = "UPDATE_FILTER_SUCCESS";
export const FILTERS_ERROR = "FILTERS_ERROR";
