export const FETCHING_COMMENTS = "FETCHING_COMMENTS";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const ADDING_COMMENT = "ADDING_COMMENT";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const COMMENTS_ERROR = "COMMENTS_ERROR";
export const REMOVING_COMMENTS_RELATIVE_TASK =
  "REMOVING_COMMENTS_RELATIVE_TASK";
export const REMOVE_COMMENTS_RELATIVE_TASK_SUCCESS =
  "REMOVE_COMMENTS_RELATIVE_TASK_SUCCESS";
