export const FETCHING_FILES = "FETCHING_FILES";
export const FETCH_FILES_SUCCESS = "FETCH_FILES_SUCCESS";
export const ADDING_FILE = "ADDING_FILE";
export const ADD_FILE_SUCCESS = "ADD_FILE_SUCCESS";
export const REMOVING_FILE = "REMOVING_FILE";
export const REMOVE_FILE_SUCCESS = "REMOVE_FILE_SUCCESS";
export const FILES_ERROR = "FILES_ERROR";
