export const FETCHING_PAYMENTS = "FETCHING_PAYMENTS";
export const FETCH_PAYMENTS_SUCCESS = "FETCH_PAYMENTS_SUCCESS";
export const FETCHING_LAST_INSERT_INVOICE = "FETCHING_LAST_INSERT_INVOICE";
export const FETCH_LAST_INSERT_INVOICE_SUCCESS =
  "FETCH_LAST_INSERT_INVOICE_SUCCESS";
export const FETCHING_LAST_INSERT_PATTERN = "FETCHING_LAST_INSERT_PATTERN";
export const FETCH_LAST_INSERT_PATTERN_SUCCESS =
  "FETCH_LAST_INSERT_PATTERN_SUCCESS";
export const ADDING_PAYMENT = "ADDING_PAYMENT";
export const ADD_PAYMENT_SUCCESS = "ADD_PAYMENT_SUCCESS";
export const REMOVING_PAYMENT = "REMOVING_PAYMENT";
export const REMOVE_PAYMENT_SUCCESS = "REMOVE_PAYMENT_SUCCESS";
export const UPDATING_PAYMENT = "UPDATING_PAYMENT";
export const UPDATE_PAYMENT_SUCCESS = "UPDATE_PAYMENT_SUCCESS";
export const PAYMENTS_ERROR = "PAYMENTS_ERROR";
