export const FETCHING_MESSENGERS = "FETCHING_MESSENGERS";
export const FETCH_MESSENGERS_SUCCESS = "FETCH_MESSENGERS_SUCCESS";
export const UPDATING_MESSENGER = "UPDATING_MESSENGER";
export const UPDATE_MESSENGER_SUCCESS = "UPDATE_MESSENGER_SUCCESS";
export const MESSENGERS_ERROR = "MESSENGERS_ERROR";
