export const ADDING_MESSENGER = "ADDING_MESSENGER";
export const ADD_MESSEGNER_SUCCESS = "ADD_MESSEGNER_SUCCESS";
export const FETCHING_MESSENGERS_BY_NAME = "FETCHING_MESSENGERS_BY_NAME";
export const FETCH_MESSENGERS_BY_NAME_SUCCESS =
  "FETCH_MESSENGERS_BY_NAME_SUCCESS";
export const UPDATING_MESSENGER = "UPDATING_MESSENGER";
export const UPDATE_MESSENGER_SUCCESS = "UPDATE_MESSENGER_SUCCESS";
export const MESSENGERS_ERROR = "MESSENGERS_ERROR";
