export const SENDING_MAIL = "SENDING_MAIL";
export const SEND_MAIL_SUCCESS = "SEND_MAL_SUCCESS";
export const MAIL_ERRORS = "MAIL_ERRORS";
export const FETCHING_MAILS = "FETCHING_MAILS";
export const FETCH_MAILS_SUCCESS = "FETCH_MAILS_SUCCESS";