export const ADDING_MAIL = "ADDING_MAIL";
export const ADD_MAIL_SUCCESS = "ADD_MAL_SUCCESS";
export const MAILS_ERRORS = "MAILS_ERRORS";
export const FETCHING_MAILS = "FETCHING_MAILS";
export const FETCH_MAILS_SUCCESS = "FETCH_MAILS_SUCCESS";
