export const FETCHING_USERS_HISTORY = "FETCHING_USERS_HISTORY";
export const FETCH_USERS_HISTORY_SUCCESS = "FETCH_USERS_HISTORY_SUCCESS";
export const ADDING_USER_HISTORY = "ADDING_USER_HISTORY";
export const ADD_USER_HISTORY_SUCCESS = "ADD_USER_HISTORY_SUCCESS";
export const USERS_HISTORY_ERROR = "USERS_HISTORY_ERROR";
