export const FETCHING_TASKS = "FETCHING_TASKS";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const ADDING_TASK = "ADDING_TASK";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const REMOVING_TASK = "REMOVING_TASK";
export const REMOVE_TASK_SUCCESS = "REMOVE_TASK_SUCCESS";
export const UPDATING_TASK = "UPDATING_TASK";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
