export const FETCHING_SETTINGS = "FETCHING_SETTINGS";
export const FETCH_SETTINGS_SUCCESS = "FETCH_SETTINGS_SUCCESS";
export const UPDATING_SETTINGS = "UPDATING_SETTINGS";
export const UPDATE_SETTINGS_SUCCESS = "UPDATE_SETTINGS_SUCCESS";
export const SETTINGS_ERROR = "SETTINGS_ERROR";
